name: Build & Release Latest Wines
on:
  push:
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        _LOCAL_PRESET: [protonified, valve-exp, valve-exp-bleeding]
        distro: [archlinux, ubuntu, fedora]
        wine_type: [proton, standard]
    uses: ./.github/workflows/wine-builder.yml
    with:
      distro: ${{ matrix.distro }}
      _LOCAL_PRESET: ${{ matrix._LOCAL_PRESET }}
      wine_type: ${{ matrix.wine_type }}

  make-release:

    runs-on: ubuntu-latest

    needs:
      - "build"

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4

      - name: Get current date
        id: date
        run: |
          dateval=$(date +'%Y-%m-%d')
          echo "date='$dateval'" >> $GITHUB_OUTPUT

      - name: Couting artifact number
        id: count-artifacts
        run: |
          artifact_num=`find . -ipath "*proton-tkg*" -or -ipath "*wine-tkg*" | wc -l`
          echo "artifact_num='$artifact_num'" >> $GITHUB_OUTPUT

      - name: Make new release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.count-artifacts.outputs.artifact_num != '0'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.date.outputs.date }}
          prerelease: false
          title: "Wine builds ${{ steps.date.outputs.date }}"
          files: |
            ${{ github.workspace }}/proton-tkg-*/**
            ${{ github.workspace }}/wine-tkg-*/**
